# Generated by Django 2.2.23 on 2021-05-19 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('default_callback', models.CharField(blank=True, help_text='Enter the path name for a view that will verify the transaction.', max_length=255, null=True, verbose_name='Redirect to')),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateways',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('amount', models.IntegerField(verbose_name='Amount (IRR)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('token', models.TextField(blank=True, null=True, unique=True, verbose_name='Token')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Account')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payir.Gateway', verbose_name='Gateway')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-modified'],
            },
        ),
    ]
