# Generated by Django 2.2.23 on 2021-05-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='default_redirect_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
