# Generated by Django 2.2.23 on 2021-08-15 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('base', '0001_initial'),
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribers', to='base.Profile'),
        ),
    ]
