# Generated by Django 2.2.23 on 2021-08-15 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('base', '0001_initial'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='serial',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='serial_subscribers', to='base.Profile'),
        ),
        migrations.AddField(
            model_name='episode',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='base.Category'),
        ),
        migrations.AddField(
            model_name='episode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Profile'),
        ),
        migrations.AddField(
            model_name='episode',
            name='serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='series.Serial'),
        ),
        migrations.AddField(
            model_name='episode',
            name='video_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.File'),
        ),
    ]
